name: Alpine Linux CI

on:
  push:
    branches: [main]
    paths:
      - docker/build.Dockerfile
      - .github/workflows/docker-ci.yml
  pull_request:
    branches: [main]

env:
  # Needed to ensure GitHub CLI is hydrated with our bot's PAT
  GITHUB_TOKEN: ${{secrets.GH_SERVICE_ACCOUNT_API_TOKEN}}

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hydrate GitHub CLI to bump ratelimits
      run: |
        echo ${{secrets.GH_SERVICE_ACCOUNT_API_KEY}} | gh auth login --with-token
        gh auth status
    - name: Install Dive
      run: |
        curl -s --compressed "https://madebythepinshub.gitlab.io/ppa/releases-key.gpg" | sudo apt-key add -;
        echo "deb https://madebythepinshub.gitlab.io/ppa ./" | sudo tee /etc/apt/sources.list.d/thepinsteam-ppa-gitlab.list
        sudo apt update; sudo apt install dive -y
    - name: Run test build and analyze size
      run: |
        NIGHTLY_RELEASE_TAG="$(gh api repos/gitpod-io/openvscode-server/releases | jq -r 'map(select(.prerelease)) | first | .tag_name' | sed -E 's/openvscode-server-//gm;t;d')"

        docker build  --file ./docker/build.Dockerfile --tag ghcr.io/gitpodify/openvscode-releases-musl/nightly:dev --build-arg=RELEASE_TAG=$NIGHTLY_RELEASE_TAG .
        
        CI=true dive ghcr.io/ghcr.io/gitpodify/openvscode-releases-musl/nightly:dev
      #env:
      #  DOCKER_BUILDKIT: "1"
    - name: Extract server-pkg from image
      run: |
        mkdir artifacts/images -p
        mkdir artifacts/builds

        CONTAINER_ID=$(docker create ghcr.io/gitpodify/openvscode-releases-musl/nightly:dev)
        docker cp $CONTAINER_ID:/home/gitpod/.gitpodified-server $GITHUB_WORKSPACE/artifacts/builds/amd64
    - name: Export as artifact
      run: docker save -o artifacts/images/openvscode-server-devbuild-amd64.tar ghcr.io/gitpodify/openvscode-releases-musl/nightly:dev
    - name: Upload image export
      uses: actions/upload-artifact@v2
      with:
        name: nightly-devpush-amd64-docker-image
        path: artifacts/images/openvscode-server-devbuild-amd64.tar
    - name: Upload tar.gz amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: nightly-devpush-amd64-builds
        path: artifacts/builds/amd64